# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lennert/HWSW/xoodyak/hwswcd/hardware/xoodyak_SOC/xoodyak_SOC.srcs/sources_1/ip/blk_mem_round_constants/blk_mem_round_constants.xci
# IP: The module: 'blk_mem_round_constants' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lennert/HWSW/xoodyak/hwswcd/hardware/xoodyak_SOC/xoodyak_SOC.gen/sources_1/ip/blk_mem_round_constants/blk_mem_round_constants_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_round_constants'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lennert/HWSW/xoodyak/hwswcd/hardware/xoodyak_SOC/xoodyak_SOC.srcs/sources_1/ip/blk_mem_round_constants/blk_mem_round_constants.xci
# IP: The module: 'blk_mem_round_constants' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lennert/HWSW/xoodyak/hwswcd/hardware/xoodyak_SOC/xoodyak_SOC.gen/sources_1/ip/blk_mem_round_constants/blk_mem_round_constants_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_round_constants'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
